#!/data/data/com.termux/files/usr/bin/bash
figlet Youtube | lolcat
figlet Downloader | lolcat 
echo -e "\e[036m" "╔════════════════════════════════════════════════════╗"                                                                          
echo -e "\e[032m" "║ ♚ Project Name : YOUTUBE DOWNLOADER                ║"
echo -e "\e[032m" "║ ♚ Youtube      : Tronian                           ║"
echo -e "\e[032m" "║ ♚ Githubb      : Github.com/Boz99                  ║"
echo -e "\e[032m" "║ ♚ Whatsapp     : http://wa.me/12342472556          ║"
echo -e "\e[036m" "╚════════════════════════════════════════════════════╝"
echo "1. Select a video on YouTube and click the share button, select Termux, then it will automatically open Termux"
echo "2. select number 1-5 as you wish"
echo "3. It will automatically download. Files are only stored in the TRONIANCHANNELYOUTUBE folder"
echo "4. for details check on video"
echo -e "\e[036m" "╠═▶⛔SELECT A FORMAT⛔ "
echo
echo -e "\e[032m" "╠═▶ 1. Music Mp3♫"
echo -e "\e[032m" "╠═▶ 2. Video 360p"
echo -e "\e[032m" "╠═▶ 3. Video 480p"
echo -e "\e[032m" "╠═▶ 4. Video 720p"
echo -e "\e[032m" "╠═▶ 5. Video 1080p"

command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/TRONIANCHANNELYOUTUBE/%(title)s.%(ext)s -f'
read -p " ╚══➤ " option

if [ "$option" -eq "1" ]
then
    echo "$command 140" > ~/.config/youtube-dl/config
    youtube-dl $1
    echo "check on folder TRONIANCHANNELYOUTUBE"

elif [ "$option" -eq "2" ]
then
    echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config
    youtube-dl $1
    echo "check on folder TRONIANCHANNELYOUTUBE"

elif [ "$option" -eq "3" ]
then
    echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config
    youtube-dl $1
    echo "check on folder TRONIANCHANNELYOUTUBE"

elif [ "$option" -eq "4" ]
then
    echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config
    youtube-dl $1
    echo "check on folder TRONIANCHANNELYOUTUBE"

elif [ "$option" -eq "5" ]
then
    echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config
    youtube-dl $1
    echo "check on folder TRONIANCHANNELYOUTUBE"

else
    echo "WRONG COBA LAGI "
fi

